version: "3"

services:
  openresty:
    image: srajasimman/openresty-prometheus:latest
    ports:
      - "80:80"
      - "9145:9145"
      - "8080:8080"
    volumes:
      - ./sites/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
